### ISSUE TITLE
请问下数据库为什么采用MongoDB？

### ISSUE THREAD

**Issue by Emcikem** [jamebal/jmal-cloud-server#10]
为什么数据库是使用MongoDB，而不是MySQL呢？

**Comment by Emcikem** [comment]
> 为什么数据库是使用MongoDB，而不是MySQL呢？

还有一个问题，请问下文件是存储在哪里的呢？

**Comment by jamebal** [comment]
> 为什么数据库是使用MongoDB，而不是MySQL呢？

用MySQL也可以，个人喜好问题

**Comment by jamebal** [comment]
在配置文件里可以指定存储路径：https://github.com/jamebal/jmal-cloud-server/blob/master/src/main/resources/file.yml

**Comment by Emcikem** [comment]
感谢聚聚，
还有个问题，请问下聚聚数据库结构是什么呀，我打不开.db文件QAQ

**Comment by jamebal** [comment]
https://github.com/lionsoul2014/ip2region
