### ISSUE TITLE
建议增加转码参数配置

### ISSUE THREAD

**Issue by kokojacket** [jamebal/jmal-cloud-server#108]
突然发现转码的参数不支持自定义。建议支持配置转码的参数。适应不同的硬件配置

**Comment by jamebal** [comment]
什么参数呢？

**Comment by jamebal** [comment]
目前只适配了nvidia独显，Intel核显和amd核显暂不支持

**Comment by jamebal** [comment]
现在有比特率和分辨率, 还需要那些参数

**Comment by kokojacket** [comment]
您理解错了🤣🤣🤣
先在这个是“需要转码的视频”标准，
我提的是“转码视频”的预生成参数，也就是希望能控制生成出来的“标清视频”的参数标准
不过这只是个不成熟的建议罢了~🤣

**Comment by jamebal** [comment]
> 您理解错了🤣🤣🤣 现在这个是“需要转码的视频”标准， 我提的是“转码视频”的预生成参数，也就是希望能控制生成出来的“标清视频”的参数标准 不过这只是个不成熟的建议罢了~🤣

现在的比特率和分辨率就是生成后的视频参数

**Comment by jamebal** [comment]
> 所以是否可以理解为，两个标准公用一个参数。

是的

**Comment by kokojacket** [comment]
> > 所以是否可以理解为，两个标准公用一个参数。
> 
> 是的

这种方式似乎不太灵活，还是建议讲两个标准分开。
例如我4K 30Mbps的视频，外网可以流畅播放。但我肯定并不希望按照这个标准来转码。会大量占用空间。转码标准可能会大大低于外网流畅播放的标准。

**Comment by jamebal** [comment]
> > > 所以是否可以理解为，两个标准公用一个参数。
> > 
> > 
> > 是的
> 
> 这种方式似乎不太灵活，还是建议讲两个标准分开。 例如我4K 30Mbps的视频，外网可以流畅播放。但我肯定并不希望按照这个标准来转码。会大量占用空间。转码标准可能会大大低于外网流畅播放的标准。

下个版本改成两种参数
