### ISSUE TITLE
如果能添加ES 就更棒了！

### ISSUE THREAD

**Issue by code-lives** [jamebal/jmal-cloud-server#116]
本来我是写php项目的，看到有人推荐这个项目，感觉非常棒。可是我想要的搜索还需要针对内容进行搜索。难道我还得学习下java。好难啊。希望作者可以添加个ES功能。就是读取 xls、pdf、word的内容 存入es 就行。分词搜索。非常膜拜作者
![image](https://github.com/jamebal/jmal-cloud-server/assets/79346591/1f9d1f47-e880-4443-97fb-9e94aca142d3)

**Comment by jamebal** [comment]
已经使用了Lucene, Elasticsearch对于这种项目来说太重了, 目前java已经很重了😂
