### ISSUE TITLE
作者您好，请问能否推出保留有nginx的容器镜像？

### ISSUE THREAD

**Issue by mawanglin** [jamebal/jmal-cloud-server#14]
您好，首先感谢你的辛苦付出为大家推出好用的私有云盘，谢谢。
但是，在v2.3.0的版本中发现已经剔除nginx和mongodb，mongodb可使用“MONGODB_URI”链接外部数据库，但是nginx则需要和jmalcloud一起部署，会多一个容器，增加部署难度，不只是否后续会推出带有nginx版本的jmalcloud，谢谢。

**Comment by jamebal** [comment]
新版部署应该是更简单了,
老版本升级可以看这里
https://blog.jmal.top/s/docker-jmalcloud

**Comment by mawanglin** [comment]
"jc.sh"脚本，我看了下内容，有需要nginx做反向代理，可否不部署Nginx，仅部署jmalcloud，然后通过“MONGODB_URI”连接外部MongoDB？

**Comment by jamebal** [comment]
现在还是需要nginx的

**Comment by mawanglin** [comment]
好，谢谢
