### ISSUE TITLE
问题描述：预览文件夹和下载文件夹未找到路径

### ISSUE THREAD

**Issue by sjgfa** [jamebal/jmal-cloud-server#15]
我看了一下controller的代码，没找到下载文件和预览文件的controller

**Comment by jamebal** [comment]
文件的预览和下载在这里:com.jmal.clouddisk.interceptor.FileInterceptor

**Comment by sjgfa** [comment]
> 文件的预览和下载在这里：[com.jmal.clouddisk.interceptor.FileInterceptor](https://github.com/jamebal/jmal-cloud-server/blob/master/src/main/java/com/jmal/clouddisk/interceptor/FileInterceptor.java)

好的，谢谢，我找到原因了，还是因为window的差异，生成的链接file.path是\，而我们的链接地址是/，我改一下代码就好了
![image](https://user-images.githubusercontent.com/53327141/211266732-6e15535f-5856-49fa-abbc-883bd1d32b16.png)
