### ISSUE TITLE
我想在 k8s 中启动 jmal-cloud

### ISSUE THREAD

**Issue by ProgrammerVsita** [jamebal/jmal-cloud-server#161]
我使用的 k8s 版本是 1.27.9，cri 版本是 containerd://1.6.31
目前 jmal 的前后端 pod 和 mongodb 以及 onlyoffice 状态都是 running 的，日志也没有报错，jmal 后端 容器内也能够正常连接上 mongodb，但是前端界面打开后提示：哎呀！服务器出错了，请稍后再试！
![企业微信截图_17268025797642](https://github.com/user-attachments/assets/2a09b350-3eac-43e2-abea-8b79a619188c)
![企业微信截图_17268026131867](https://github.com/user-attachments/assets/4102870e-c4fa-4640-92c2-d36ba337b96d)
请问我如何定位问题来在 k8s 上正常运行 jmalcloud，如果需要其他信息或者截图请说明

**Comment by jamebal** [comment]
等一下, 可能还没有完全启动

**Comment by ProgrammerVsita** [comment]
![企业微信截图_17268029185179](https://github.com/user-attachments/assets/d9163838-d387-489e-949f-5ac4c15395ad)
我g刚刚看了一下前端的日志，里面是有报错的

**Comment by jamebal** [comment]
这个错误就是界面上提示错误

**Comment by ProgrammerVsita** [comment]
是我的后端的 service 里面没有加 8088 这个端口，现在加上这个端口后已经正常了，谢谢
