### ISSUE TITLE
Onlyoffice 无法正常预览

### ISSUE THREAD

**Issue by walterfang1209** [jamebal/jmal-cloud-server#168]
如题，使用内置 `Onlyoffice` 预览 `.docx` 等文件时会出现如下弹窗：
![屏幕截图 2024-10-02 185318](https://github.com/user-attachments/assets/d77b66eb-fc3f-47ca-b3a4-261aa3695d0a)
请问是否要对 `JWT_SECRET` 进行额外配置？

**Comment by walterfang1209** [comment]
@jamebal

**Comment by jamebal** [comment]
需要在网盘设置-onlyoffice中添加密钥，该密钥为docker-compose.yml中的JWT_SECRET

**Comment by walterfang1209** [comment]
> 需要在网盘设置-onlyoffice中添加密钥，该密钥为docker-compose.yml中的JWT_SECRET

已修复，感谢。
