### ISSUE TITLE
bug：新建的txt文件，打开复制外面的内容到txt中会出现换行问题

### ISSUE THREAD

**Issue by barry200890** [jamebal/jmal-cloud-server#175]
网盘中新建txt文件后，将之前windows桌面上一个文本文件里的两行内容复制过来粘贴到网盘中打开的txt里面，本来两行内容应该都在一行，结果实际保存后，内容变成了四行。

**Comment by jamebal** [comment]
感谢反馈，可以上传windows中的这个txt文件到github试试吗

**Comment by barry200890** [comment]
[22.txt](https://github.com/user-attachments/files/17917205/22.txt)
比如这个

**Comment by jamebal** [comment]
v2.10.0已修复
