### ISSUE TITLE
mac上无法上传文件,先弹窗了输密码，输完密码提示文件已存在，文件大小0

### ISSUE THREAD

**Issue by junegod** [jamebal/jmal-cloud-server#18]
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/2197929/226095427-f85bd332-b7c5-4c8e-8efb-fcabbecb3153.png">
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/2197929/226095461-394dfe3f-5b27-460b-8943-6dd849163161.png">
<img width="440" alt="image" src="https://user-images.githubusercontent.com/2197929/226095506-4ab9d565-8175-4c7b-bc42-44f2b3b4bc3e.png">
后台报错
<img width="1549" alt="image" src="https://user-images.githubusercontent.com/2197929/226095559-cea5a2c8-b5e8-43ef-a038-89fe4d812477.png">

**Comment by jamebal** [comment]
这个密码弹窗是怎么触发的?

**Comment by junegod** [comment]
就启动项目本地，finder连接服务器http://localhost:9528/api/webDAV/admin
没有额外操作，有交流群吗

**Comment by junegod** [comment]
方便加下我微信么15666794049
