### ISSUE TITLE
关于阿里云 OSS

### ISSUE THREAD

**Issue by zn353010922** [jamebal/jmal-cloud-server#19]
我看项目配置文件中有配置阿里云 OSS的配置参数，也启用了，但是实际上传后还是存储在本地文件中，如果要上传到阿里云 OSS是需要什么特殊设置吗？还是说我的file.yml设置问题呢？https://cloud1.jmal.top/s?s=6417b95663fcf13fc914e918

**Comment by jamebal** [comment]
这功能还没加上，正在开发
