### ISSUE TITLE
 有打包的单个docker镜像吗

### ISSUE THREAD

**Issue by HoGC** [jamebal/jmal-cloud-server#34]
使用脚本安装后有多个容器，不好管理

**Comment by jamebal** [comment]
脚本就是通过docker-comose 进行管理的,最开始就是单独的docker镜像,但是单个docker镜像体积太大;你是有使用其他工具管理docker容器吗?

**Comment by HoGC** [comment]
是镜像多大会来些什么问题吗，我也是很懂，就觉得单个方便点，不然一停要停好几个，启动也是，毕竟nginx这些其实也不会去动它除了启动停止，打包成单个还是好操作点

**Comment by jamebal** [comment]
docker-compose就是用来管理多个镜像的，很方便，这个脚本在docker-compose基础上更加方便。使用 ./jc -h 查看帮助，里面有些常用的操作，重置密码也加上去了

**Comment by HoGC** [comment]
不是说脚本不方便，是一般不太会使用用脚本去操作，一般使用Portainer什么的，那就是好几个容器了，

**Comment by jamebal** [comment]
如果使用Portainer来管理确实不方便, 一般是只有在升级的时候会用脚本升级一下,平时也不会操作; 不知道你的使用场景是怎么样的

**Comment by HoGC** [comment]
你说的对，其实也没操作什么，单个也就看起来好一点，
其实也是就问问而已，没有就继续用这个了
