### ISSUE TITLE
希望优化公网访问流畅度，以及为文件添加标签功能用于检索。

### ISSUE THREAD

**Issue by kokojacket** [jamebal/jmal-cloud-server#37]
感谢大佬开发这么好用的网盘项目！
优化建议：
公网访问网盘视频、图片素材，受限于家用宽带5M/S，稍微高码率视频，大图片的加载会非常卡顿和慢，建议优化为提前预转码，公网访问时，显示的是转码图片和转码视频。只有下载或者点击查看原图的是，再播放源文件。

比如导入文件后，每天凌晨2点，后台转码素材为webp图片，转码视频为720Ph264编码小文件。
日常访问就只访问转码优化后的文件。会显的极为流畅。

**Comment by jamebal** [comment]
好建议!

**Comment by kokojacket** [comment]
非常期待！标签系统以及转码优化~！！！急死我了！
