### ISSUE TITLE
如何启用https

### ISSUE THREAD

**Issue by Xiaoph123** [jamebal/jmal-cloud-server#40]
![mmexport1715188205422.png](https://github.com/jamebal/jmal-cloud-server/assets/106538519/b9426363-cabe-4841-b5a2-c9742eae05fd)

大佬好，如图，我使用docker安装启动后，默认用的是HTTP，我如何改成https，望您抽空解答一下，我不太懂怎么设置，还请麻烦您详细讲解一下

**Comment by jamebal** [comment]
需要使用其他http服务器(比如nginx)代理网盘地址

**Comment by Xiaoph123** [comment]
> 需要使用其他http服务器(比如nginx)代理网盘地址, 你是在内网使用还是公网使用

我是公网访问

**Comment by Xiaoph123** [comment]
> 需要使用其他http服务器(比如nginx)代理网盘地址, 你是在内网使用还是公网使用

感谢大佬已解决
