### ISSUE TITLE
希望可以支持压缩文件在服务端解压缩

### ISSUE THREAD

**Issue by gzxiexl** [jamebal/jmal-cloud-server#42]
感谢大佬开发的网盘项目！非常好用。
希望能够支持压缩文件在服务端解压缩，节省带宽。

**Comment by gzxiexl** [comment]
> 感谢大佬开发的网盘项目！非常好用。
> 希望能够支持压缩文件在服务端解压缩，节省带宽。

发现 ip 格式的压缩包可以， 7z 的压缩包无法解压缩，服务器端如果可以压缩文件夹就更好了。

**Comment by jamebal** [comment]
#118
