### ISSUE TITLE
希望可以支持本地目录功能

### ISSUE THREAD

**Issue by Bmixo** [jamebal/jmal-cloud-server#43]
目前是从fileDocument里面读取文件列表，不方便管理已经存在的大目录多文件，这种情况文件同步功能不好用

**Comment by jamebal** [comment]
**1. 本地路径扫描**: 需要在docker-compose.yml文件中添加挂载路径
   例如: 
   我想添加系统文件夹`/home/test/doc`挂载到网盘, 用户名为`admin`下的文件夹中(必须挂载到某个用户下,否则扫描不到)
   需要在volumes加上
  ```yml
volumes:
      - xxxx:/jmalcloud/files
      - /home/test/doc:/jmalcloud/files/admin/doc
```
   使用`docker-cmpose up -d`重启后, 在网盘设置中点击重建索引, 该操作会扫描整个`/jmalcloud/files`目录, 扫面完成后 
   `/home/test/doc`目录会出现在`admin`用户下文件夹中

   **⚠️注意:**  volumes下挂载的文件夹需要相互独立, 例如: 
  ```yml
volumes:
      - /home/test/doc/files:/jmalcloud/files
      - /home/test/doc:/jmalcloud/files/admin/doc
# /home/test/doc 包含了 /home/test/doc/files
```

**Comment by Bmixo** [comment]
> 在网盘设置中点击重建索引

添加直接访问本地目录的功能的目的主要是可以实现类似Alist管理外部存储的效果，因为本地目录很大，很多小文件，而且是挂载多个云存储供应商到本地的，因此重建索引全部扫描一次目录会消耗大量的时间。

![image](https://github.com/jamebal/jmal-cloud-server/assets/25509024/0e4decd0-c532-4057-97fd-7266e23cd113)
g

![image](https://github.com/jamebal/jmal-cloud-server/assets/25509024/152ac76c-4b54-4f19-bc02-3859573a41b8)
这里的文件夹和路径都带有ID，其实我觉得可以在contentype里多加一个 本地目录类型 来标识本地存储的类型,这样也不影响fileDocument的逻辑，默认目录的话使用原先的文件处理逻辑，如果是本地目录的话则使用本地文件处理逻辑

**Comment by jamebal** [comment]
后面重建索引优化下, 根据指定目录扫描

**Comment by jamebal** [comment]
v2.9.0版本右键文件夹详情可以单独扫描该目录
