### ISSUE TITLE
请问如何开启视频转码功能

### ISSUE THREAD

**Issue by kokojacket** [jamebal/jmal-cloud-server#67]
请问如何开启视频转码功能

**Comment by jamebal** [comment]
上传完视频文件后, 后台会自动转为低码率视频

**Comment by jamebal** [comment]
<img width="481" alt="截屏2024-05-27 11 33 13" src="https://github.com/jamebal/jmal-cloud-server/assets/49510841/76644bf6-bf0f-4f79-b409-6011356d29ea">

转码完成后多出一个`HD`的选项. 

如果视频分辨率小于720p且码率小于2500kbps, 则不会转码

**Comment by jamebal** [comment]
目前没有配置选项

**Comment by kokojacket** [comment]
好滴~
