### ISSUE TITLE
上传文件点击了最小化后上传消失了

### ISSUE THREAD

**Issue by kokojacket** [jamebal/jmal-cloud-server#68]
![recording](https://github.com/jamebal/jmal-cloud-server/assets/74887370/833b6b6f-f944-466d-aded-c2c70911a2c0)

**Comment by jamebal** [comment]
最后文件上传成了没有

**Comment by kokojacket** [comment]
没有

**Comment by kokojacket** [comment]
![image](https://github.com/jamebal/jmal-cloud-server/assets/74887370/2e51a647-f5d8-412c-b8a7-6d28334e9852)
后台cpu好像下不来了🤣

**Comment by jamebal** [comment]
是上传了视频吗, 转码比较耗资源

**Comment by kokojacket** [comment]
是的，上传了视频。后台看不到转码进度，所以有点不清楚。

**Comment by jamebal** [comment]
纯CPU转码比较慢
