### ISSUE TITLE
小小建议

### ISSUE THREAD

**Issue by kokojacket** [jamebal/jmal-cloud-server#69]
再次感谢大佬开发这么好用的网盘项目！
许愿：
1、搜索框能支持搜索标签。
2、文件信息希望能体现更多数据源信息、比如视频的码率、分辨率；照片的光圈、iso、拍摄日期等等
3、后台可以自定义视频转码的需求大小
4、后台可以预览视频、图片转码进度

**Comment by jamebal** [comment]
目前搜索框可以搜索标签

**Comment by kokojacket** [comment]
啊，真的！！！
完美

**Comment by kokojacket** [comment]
多用户挂载文件夹管理不支持添加标签等其他权限，目前只支持上传、下载、创建副本。建议增加更多权限例如添加标签。管理标签。

**Comment by jamebal** [comment]
> 多用户挂载文件夹管理不支持添加标签等其他权限，目前只支持上传、下载、创建副本。建议增加更多权限例如添加标签。管理标签。
可以的

**Comment by jamebal** [comment]
v2.9.0版本加入了这些功能
