### ISSUE TITLE
多个用户是否可以共同管理一个网盘？

### ISSUE THREAD

**Issue by kokojacket** [jamebal/jmal-cloud-server#71]
是否可以实现，多个用户共同管理一个网盘内容。不同用户拥有不同权限，部分只可以阅读，部分可以上传，部分是管理员。等等

**Comment by jamebal** [comment]
目前可通过管理用户分享某个文件夹, 其他用户挂载该文件夹来实现

**Comment by kokojacket** [comment]
如何挂载其他用户分享的文件夹？

**Comment by kokojacket** [comment]
哦发现了

**Comment by kokojacket** [comment]
请问，修改权限和删除权限的区别是什么🤣

**Comment by jamebal** [comment]
修改权限可以编辑文件内容

**Comment by kokojacket** [comment]
好像目前没有注册系统吧，用户前端是不能自己注册的吧

**Comment by kokojacket** [comment]
> 目前可通过管理用户分享某个文件夹, 其他用户挂载该文件夹来实现

太天才了，太牛了！！！！！！

**Comment by jamebal** [comment]
> 好像目前没有注册系统吧，用户前端是不能自己注册的吧

目前没有注册功能, 用户需要管理员手动添加

**Comment by kokojacket** [comment]
谢谢解答！！
