### ISSUE TITLE
目前没有配置选项

### ISSUE THREAD

**Issue by death4444** [jamebal/jmal-cloud-server#78]
目前没有配置选项

_Originally posted by @jamebal in https://github.com/jamebal/jmal-cloud-server/issues/67#issuecomment-2132584910_

建议还是可以做一个视频转码的开关
![image](https://github.com/jamebal/jmal-cloud-server/assets/26320543/cce86666-ea54-4766-a615-62feba950cad)

我这视频多的，而且大多是工作培训视频，用不着转码。
不能关闭转码，导致服务器资源一直被占用，影响服务器上的其他项目了都。
![image](https://github.com/jamebal/jmal-cloud-server/assets/26320543/22cf2a68-6619-4bd7-bcb8-983c1022a7a1)

放这里就好，嘻嘻

**Comment by jamebal** [comment]
后续加上

**Comment by jamebal** [comment]
v2.9.0加上了配置项
